//photos teeshirt men
const teeshirt_design = [
    {
        id:1,
        attachment:"images/teeshirt_design/Canevas_oh-artwork.jpg",
        alt:"photo"
    },
    {
        id:2,
        attachment:"images/teeshirt_design/Shirt.jpg",
        alt:"photo"
    },
    {
        id:3,
        attachment:"images/teeshirt_design/vocabulary.jpg",
        alt:"photo"
    },
    {
        id:4,
        attachment:"images/teeshirt_design/Bete_roudil.jpg",
        alt:"photo"
    },
    {
        id:5,
        attachment:"images/teeshirt_design/artho.jpg",
        alt:"photo"
    },
    {
        id:6,
        attachment:"images/teeshirt_design/encre_acrylique_contrast.jpg",
        alt:"photo"
    },
    {
        id:7,
        attachment:"images/teeshirt_design/Ras-Invert.jpg",
        alt:"photo"
    },
    {
        id:8,
        attachment:"images/teeshirt_design/reve_aquatic_de larbre.jpg",
        alt:"photo"
    }
]